# Refer to the documentation : https://crates.io/crates/cargo-make

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]
dependencies = ["clean"]

[tasks.clippy]
install_crate = "rustfmt"
command = "cargo"
args = ["clippy", "--","-D","warnings"]
dependencies = ["format"]

[tasks.test]
install_crate = "cargo-nextest"
command = "cargo"
args = ["nextest", "run"]
dependencies = ["clippy"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["test"]

[tasks.stats]
script = '''
#!/usr/bin/env bash
cargo install tokei && tokei
'''
dependencies = ["build"]

[tasks.runner]
run_task = [
    { name = ["stats"] },
]