pub mod binary_expression;
pub mod declarations;
pub mod identifier_declaration;
pub mod literal_declaration;
pub mod objects;
pub mod parser;
pub mod program_declaration;
pub mod variable_declaration;
pub mod variable_declarator;
