[package]
name = "errors"
version = "0.1.0"
edition = "2021"
authors = ["Mwangi Kariuki <dmwangi@kineticengines.co.ke>"]
repository = "https://github.com/daviddexter/karis-programming-language/errors"


[dependencies]
pyo3 = "0.16.5"
rustyline = "10.0.0"
