[package]
name = "console"
version = "0.1.0"
edition = "2021"
authors = ["Mwangi Kariuki <dmwangi@kineticengines.co.ke>"]
rust-version = "1.56.0"
repository = "https://github.com/daviddexter/wanja-programming-language/console/"


[dependencies]
clap = { version = "3.2.12", features = ["cargo"] }
lexer = { path = "../lexer" }
parser = { path = "../parser" }

